# Admin credentials
admin_password = "admin123"

# API Keys
gemini_api_key = "AIzaSyDgXTOjepYdcLrEc0zc20rWZAFR5297VfQ"

# Database configuration
db_path = "garment_database.db"

# Gemini API Configuration
gemini_temperature = 0.7
gemini_top_p = 0.8
gemini_top_k = 40
gemini_max_output_tokens = 2048